# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Word.seed(:text,
          {:text => 'abalone', :meaning => 'any of various large edible marine gastropods of the genus Haliotis having an ear-shaped shell with pearly interior'},
          {:text => 'abattoir', :meaning => 'a building where animals are butchered'},
          {:text => 'aberrant', :meaning => 'markedly different from an accepted norm'},
          {:text => 'abhorrent', :meaning => 'offensive to the mind'},
          {:text => 'abjuration', :meaning => 'a disavowal or taking back of a previous assertion'},
          {:text => 'ablution', :meaning => "the ritual washing of a priest's hands or of sacred vessels"},
          {:text => 'abscess', :meaning => 'symptom consisting of a localized collection of pus surrounded by inflamed tissue'},
          {:text => 'abstinence', :meaning => 'the trait of abstaining (especially from alcohol)'},
          {:text => 'abusively', :meaning => 'in an abusive manner'},
          {:text => 'abysmal', :meaning => 'very great'},
          {:text => 'accelerate', :meaning => 'move faster'},
          {:text => 'accolade', :meaning => 'a tangible symbol signifying approval or distinction'},
          {:text => 'achromatic', :meaning => 'having no hue'},
          {:text => 'acoustics', :meaning => 'the study of the physical properties of sound'},
          {:text => 'acrimony', :meaning => 'a rough and bitter manner'},
          {:text => 'addendum', :meaning => 'textual matter that is added onto a publication'},
          {:text => 'adjacent', :meaning => 'nearest in space or position'},
          {:text => 'adjudicate', :meaning => 'put on trial or hear a case and sit as the judge at the trial of'},
          {:text => 'admeasure', :meaning => "determine the quantity of someone's share"},
          {:text => 'admonitory', :meaning => 'serving to warn'},
          {:text => 'adumbrate', :meaning => 'describe roughly or briefly or give the main points or summary of'},
          {:text => 'afferent', :meaning => 'of nerves and nerve impulses'},
          {:text => 'affluence', :meaning => 'abundant wealth'},
          {:text => 'agglomeration', :meaning => 'a jumbled collection or mass'},
          {:text => 'agitator', :meaning => 'one who agitates'},
          {:text => 'aleatory', :meaning => 'dependent on chance'},
          {:text => 'allegretto', :meaning => 'in a moderately quick tempo'},
          {:text => 'amalgam', :meaning => 'an alloy of mercury with another metal (usually silver) used by dentists to fill cavities in teeth'},
          {:text => 'amanuensis', :meaning => 'someone skilled in the transcription of speech (especially dictation)'},
          {:text => 'ambidextrous', :meaning => 'equally skillful with each hand'},
          {:text => 'ambient', :meaning => 'completely enveloping'},
          {:text => 'ambiguity', :meaning => 'an expression whose meaning cannot be determined from its context'},
          {:text => 'ambuscade', :meaning => 'the act of concealing yourself and lying in wait to attack by surprise'},
          {:text => 'amenable', :meaning => 'disposed or willing to comply'},
          {:text => 'ammeter', :meaning => 'a meter that measures the flow of electrical current in amperes'},
          {:text => 'anachronous', :meaning => 'chronologically misplaced'},
          {:text => 'anaglyph', :meaning => 'moving or still pictures in contrasting colors that appear three-dimensional when superimposed'},
          {:text => 'analgesic', :meaning => 'capable of relieving pain'},
          {:text => 'anaphoric', :meaning => 'relating to anaphora'},
          {:text => 'anathema', :meaning => 'a detested person'},
          {:text => 'anchovy', :meaning => 'tiny fishes usually canned or salted'},
          {:text => 'andiron', :meaning => 'metal supports for logs in a fireplace'},
          {:text => 'anisette', :meaning => 'liquorice-flavored usually colorless sweet liqueur made from aniseed'},
          {:text => 'antagonistic', :meaning => 'indicating opposition or resistance'},
          {:text => 'anthropoid', :meaning => 'resembling apes'},
          {:text => 'antibiotic', :meaning => 'of or relating to antibiotic drugs n 1: a chemical substance derivable from a mold or bacterium that can kill microorganisms and cure bacterial infections'},
          {:text => 'antidote', :meaning => 'a remedy that stops or controls the effects of a poison'},
          {:text => 'antiphony', :meaning => 'alternate (responsive) singing by a choir in two parts'},
          {:text => 'antiseptic', :meaning => 'thoroughly clean and free of or destructive to disease- causing organisms'},
          {:text => 'aphasia', :meaning => 'inability to use or understand language (spoken or written) because of a brain lesion'},
          {:text => 'apologia', :meaning => 'a formal written defense of something you believe in strongly'},
          {:text => 'apostate', :meaning => 'not faithful to religion or party or cause n 1: a disloyal person who betrays or deserts his cause or religion or political party or friend etc.'},
          {:text => 'apprehensible', :meaning => 'capable of being apprehended or understood'},
          {:text => 'approbation', :meaning => 'official approval'},
          {:text => 'aquamarine', :meaning => 'a transparent variety of beryl that is blue green in color'},
          {:text => 'aquiline', :meaning => "curved down like an eagle's beak"},
          {:text => 'arabesque', :meaning => 'position in which the dancer has one leg raised behind and arms outstretched in a conventional pose'},
          {:text => 'arduousness', :meaning => 'extreme effortfulness'},
          {:text => 'arthritis', :meaning => 'inflammation of a joint or joints'},
          {:text => 'ascender', :meaning => 'someone who ascends'},
          {:text => 'assailant', :meaning => 'someone who attacks'},
          {:text => 'assiduous', :meaning => 'marked by care and persistent effort'},
          {:text => 'assonance', :meaning => 'the repetition of similar vowels in the stressed syllables of successive words'},
          {:text => 'astigmatism', :meaning => '(ophthalmology) impaired eyesight resulting usually from irregular conformation of the cornea'},
          {:text => 'astrology', :meaning => 'a pseudoscience claiming divination by the positions of the planets and sun and moon'},
          {:text => 'atheism', :meaning => 'the doctrine or belief that there is no God'},
          {:text => 'atrocious', :meaning => 'shockingly brutal or cruel'},
          {:text => 'avionics', :meaning => 'science and technology of electronic systems and devices for aeronautics and astronautics'},
          {:text => 'babushka', :meaning => "a woman's headscarf folded into a triangle and tied under the chin"},
          {:text => 'bacteriology', :meaning => 'the branch of medical science that studies bacteria in relation to disease'},
          {:text => 'bagatelle', :meaning => 'a light piece of music for piano'},
          {:text => 'balalaika', :meaning => 'a stringed instrument that has a triangular body and three strings'},
          {:text => 'balbriggan', :meaning => 'a cotton knit fabric used for underwear'},
          {:text => 'ballast', :meaning => 'any heavy material used to stabilize a ship or airship'},
          {:text => 'ballerina', :meaning => 'a female ballet dancer'},
          {:text => 'ballistic', :meaning => 'relating to or characteristic of the motion of objects moving under their own momentum and the force of gravity'},
          {:text => 'bamboozle', :meaning => "conceal one's true motives from especially by elaborately feigning good intentions so as to gain an end"},
          {:text => 'banality', :meaning => 'a trite or obvious remark'},
          {:text => 'barleycorn', :meaning => 'a grain of barley'},
          {:text => 'barometer', :meaning => 'an instrument that measures atmospheric pressure'},
          {:text => 'baroness', :meaning => 'a noblewoman who holds the rank of baron or who is the wife or widow of a baron'},
          {:text => 'barratry', :meaning => 'traffic in ecclesiastical offices or preferments'},
          {:text => 'basilica', :meaning => 'an early Christian church designed like a Roman basilica'},
          {:text => 'bassoonist', :meaning => 'a musician who plays the bassoon'},
          {:text => 'bathymetry', :meaning => 'measuring the depths of the oceans'},
          {:text => 'batiste', :meaning => 'a thin plain-weave cotton or linen fabric'},
          {:text => 'bazooka', :meaning => 'a portable rocket launcher used by infantrymen as an antitank weapon'},
          {:text => 'beatitude', :meaning => 'a state of supreme happiness'},
          {:text => 'belladonna', :meaning => 'perennial Eurasian herb with reddish bell-shaped flowers and shining black berries'},
          {:text => 'benefice', :meaning => 'an endowed church office giving income to its holder'},
          {:text => 'bereavement', :meaning => 'state of sorrow over the death or departure of a loved one'},
          {:text => 'bishopric', :meaning => 'the territorial jurisdiction of a bishop'},
          {:text => 'blatancy', :meaning => 'the property of being both obvious and offensive'},
          {:text => 'blooper', :meaning => 'an embarrassing mistake'},
          {:text => 'bludgeon', :meaning => 'a club used as a weapon v 1: overcome or coerce as if by using a heavy club'},
          {:text => 'caboodle', :meaning => 'any collection in its entirety'},
          {:text => 'cacophony', :meaning => 'a loud harsh or strident noise'},
          {:text => 'cadaver', :meaning => 'the dead body of a human being'},
          {:text => 'calamitous', :meaning => '(of events) having extremely unfortunate or dire consequences'},
          {:text => 'calculus', :meaning => 'a hard lump produced by the concretion of mineral salts'},
          {:text => 'calisthenics', :meaning => 'the practice of calisthenic exercises'},
          {:text => 'calligrapher', :meaning => 'someone skilled in penmanship'},
          {:text => 'camouflage', :meaning => 'an outward semblance that misrepresents the true nature of something'},
          {:text => 'campanile', :meaning => 'a bell tower'},
          {:text => 'camphor', :meaning => 'a resin obtained from the camphor tree'},
          {:text => 'camwood', :meaning => 'small shrubby African tree with hard wood used as a dyewood yielding a red dye'},
          {:text => 'candelabrum', :meaning => 'branched candlestick'},
          {:text => 'cannibalism', :meaning => 'the practice of eating the flesh of your own kind'},
          {:text => 'cannonade', :meaning => 'intense and continuous artillery fire'},
          {:text => 'canorous', :meaning => 'richly melodious'},
          {:text => 'cantankerous', :meaning => 'stubbornly obstructive and unwilling to cooperate'},
          {:text => 'capacitance', :meaning => 'an electrical phenomenon whereby an electric charge is stored'},
          {:text => 'capillary', :meaning => 'of or relating to hair'},
          {:text => 'capsize', :meaning => 'overturn accidentally'},
          {:text => 'carnivorous', :meaning => 'relating to or characteristic of carnivores'},
          {:text => 'carotid', :meaning => 'of or relating to either of the two major arteries supplying blood to the head and neck'},
          {:text => 'carrion', :meaning => 'the dead and rotting body of an animal'},
          {:text => 'cartilage', :meaning => 'tough elastic tissue'},
          {:text => 'casserole', :meaning => 'food cooked and served in a casserole'},
          {:text => 'casuistry', :meaning => 'argumentation that is specious or excessively subtle and intended to be misleading'},
          {:text => 'catacomb', :meaning => 'an underground tunnel with recesses where bodies were buried (as in ancient Rome)'},
          {:text => 'catalytic', :meaning => 'relating to or causing or involving catalysis'},
          {:text => 'catarrh', :meaning => 'inflammation of the nose and throat with increased production of mucus'},
          {:text => 'catatonic', :meaning => 'characterized by catatonia especially either rigidity or extreme laxness of limbs'},
          {:text => 'catechism', :meaning => 'a series of question put to an individual (such as a political candidate) to elicit their views'},
          {:text => 'cavalcade', :meaning => 'a procession of people traveling on horseback'},
          {:text => 'centurion', :meaning => '(ancient Rome) the leader of 100 soldiers'},
          {:text => 'ceremonious', :meaning => 'characterized by pomp and ceremony and stately display'},
          {:text => 'chancellor', :meaning => 'the British cabinet minister responsible for finance'},
          {:text => 'chandelier', :meaning => 'branched lighting fixture'},
          {:text => 'chapeau', :meaning => 'headdress that protects the head from bad weather'},
          {:text => 'chateaubriand', :meaning => 'French statesman and writer'},
          {:text => 'chattel', :meaning => 'personal as opposed to real property'},
          {:text => 'chauvinistic', :meaning => 'of or relating to persons convinced of the superiority of their own gender or kind'},
          {:text => 'chenille', :meaning => 'a soft tufted cord used in embroidery'},
          {:text => 'cherubic', :meaning => 'having a sweet nature befitting an angel or cherub'},
          {:text => 'cheviot', :meaning => 'hardy hornless sheep of the Cheviot Hills noted for its short thick wool'},
          {:text => 'chihuahua', :meaning => 'a city in northern Mexico in the state of Chihuahua'},
          {:text => 'chimerical', :meaning => 'being or relating to or like a chimera'},
          {:text => 'chinchilla', :meaning => 'the expensive silvery grey fur of the chinchilla'},
          {:text => 'chiropodist', :meaning => 'a specialist in care for the feet'},
          {:text => 'choleric', :meaning => 'easily moved to anger'},
          {:text => 'chrysalis', :meaning => 'pupa of a moth or butterfly enclosed in a cocoon'},
          {:text => 'chrysanthemum', :meaning => 'the flower of a chrysanthemum plant'},
          {:text => 'churlish', :meaning => 'rude and boorish'},
          {:text => 'circumlocution', :meaning => 'a style that involves indirect ways of expressing things'},
          {:text => 'cirrhosis', :meaning => 'a chronic disease interfering with the normal functioning of the liver'},
          {:text => 'clairvoyance', :meaning => 'apparent power to perceive things that are not present to the senses'},
          {:text => 'classicist', :meaning => 'an artistic person who adheres to classicism'},
          {:text => 'clientele', :meaning => 'customers collectively'},
          {:text => 'coadjutor', :meaning => 'an assistant to a bishop'},
          {:text => 'coalition', :meaning => 'an organization of people (or countries) involved in a pact or treaty'},
          {:text => 'cockatoo', :meaning => 'white or light-colored crested parrot of the Australian region'},
          {:text => 'cockleshell', :meaning => 'a small light flimsy boat'},
          {:text => 'collaborator', :meaning => 'someone who assists in a plot'},
          {:text => 'collateral', :meaning => 'descended from a common ancestor but through different lines'},
          {:text => 'collimate', :meaning => 'make or place parallel to something'},
          {:text => 'colloquialism', :meaning => 'a colloquial expression'},
          {:text => 'colonnade', :meaning => 'structure consisting of a row of evenly spaced columns'},
          {:text => 'colophon', :meaning => "a publisher's emblem printed in a book (usually on the title page)"},
          {:text => 'comestible', :meaning => 'suitable for use as food'},
          {:text => 'commensurate', :meaning => 'corresponding in size or degree or extent'},
          {:text => 'commiseration', :meaning => 'a feeling of sympathy and sorrow for the misfortunes of others'},
          {:text => 'commissary', :meaning => 'a retail store that sells equipment and provisions (usually to military personnel)'},
          {:text => 'compatible', :meaning => 'able to exist and perform in harmonious or agreeable combination'},
          {:text => 'compendium', :meaning => 'a publication containing a variety of works'},
          {:text => 'conacaste', :meaning => 'tropical South American tree having a wide-spreading crown of bipinnate leaves and coiled ear-shaped fruits'},
          {:text => 'conceivably', :meaning => 'within the realm of possibility'},
          {:text => 'concentric', :meaning => 'having a common center'},
          {:text => 'conchology', :meaning => 'the collection and study of mollusc shells'},
          {:text => 'concierge', :meaning => 'a French caretaker of apartments or a hotel'},
          {:text => 'concomitant', :meaning => 'following or accompanying as a consequence'},
          {:text => 'condign', :meaning => 'fitting or appropriate and deserved'},
          {:text => 'condiment', :meaning => 'a preparation (a sauce or relish or spice) to enhance flavor or enjoyment'},
          {:text => 'conduit', :meaning => 'a passage (a pipe or tunnel) through which water or electric wires can pass'},
          {:text => 'conflagration', :meaning => 'a very intense and uncontrolled fire'},
          {:text => 'confluence', :meaning => 'a place where things merge or flow together (especially rivers)'},
          {:text => 'congenital', :meaning => 'present at birth but not necessarily hereditary'},
          {:text => 'conglomerate', :meaning => 'composed of heterogeneous elements gathered into a mass'},
          {:text => 'congruent', :meaning => 'corresponding in character or kind'},
          {:text => 'conjugal', :meaning => 'of or relating to marriage or to the relationship between a wife and husband'},
          {:text => 'conjuration', :meaning => 'a ritual recitation of words or sounds believed to have a magical effect'},
          {:text => 'connoisseur', :meaning => 'an expert able to appreciate a field'},
          {:text => 'connote', :meaning => 'express or state indirectly'},
          {:text => 'connubial', :meaning => 'in a conjugal manner'},
          {:text => 'consistory', :meaning => 'a church tribunal or governing body'},
          {:text => 'consomme', :meaning => 'clear soup usually of beef or veal or chicken'},
          {:text => 'consummate', :meaning => 'having or revealing supreme mastery or skill'},
          {:text => 'contemporaneous', :meaning => 'occurring in the same period of time'},
          {:text => 'contemptuous', :meaning => 'expressing extreme contempt'},
          {:text => 'contretemps', :meaning => 'an awkward clash'},
          {:text => 'conundrum', :meaning => 'a difficult problem'},
          {:text => 'convergent', :meaning => 'tending to come together from different directions'},
          {:text => 'convivial', :meaning => 'occupied with or fond of the pleasures of good company'},
          {:text => 'convolute', :meaning => 'rolled longitudinally upon itself'},
          {:text => 'copious', :meaning => 'large in number or quantity (especially of discourse)'},
          {:text => 'coquettishly', :meaning => 'in a flirtatious manner'},
          {:text => 'cordaites', :meaning => 'tall Paleozoic trees superficially resembling modern screw pines'},
          {:text => 'coroner', :meaning => 'a public official who investigates by inquest any death not due to natural causes'},
          {:text => 'corporeal', :meaning => 'having material or physical form or substance'},
          {:text => 'corpulent', :meaning => 'excessively fat'},
          {:text => 'corpuscle', :meaning => '(nontechnical usage) a tiny piece of anything'},
          {:text => 'correlative', :meaning => 'mutually related'},
          {:text => 'corridor', :meaning => 'an enclosed passageway'},
          {:text => 'corrosive', :meaning => 'of a substance, especially a strong acid'},
          {:text => 'corrugate', :meaning => 'fold into ridges'},
          {:text => 'corruptible', :meaning => 'capable of being corrupted'},
          {:text => 'corsage', :meaning => 'an arrangement of flowers that is usually given as a present'},
          {:text => 'corvette', :meaning => 'a highly maneuverable escort warship'},
          {:text => 'cosmetology', :meaning => 'the practice of beautifying the face and hair and skin'},
          {:text => 'coterie', :meaning => 'an exclusive circle of people with a common purpose'},
          {:text => 'countenance', :meaning => "the appearance conveyed by a person's face"},
          {:text => 'counterfeit', :meaning => 'not genuine'},
          {:text => 'countermand', :meaning => 'a contrary command cancelling or reversing a previous command v 1: cancel officially'},
          {:text => 'courier', :meaning => 'a person who carries a message'},
          {:text => 'couture', :meaning => 'high fashion designing and dressmaking'},
          {:text => 'covenant', :meaning => 'a signed written agreement between two or more parties (nations) to perform some action'},
          {:text => 'covetous', :meaning => 'showing extreme cupidity'},
          {:text => 'dactylic', :meaning => 'of or consisting of dactyls'},
          {:text => 'daguerreotype', :meaning => 'a photograph made by an early photographic process'},
          {:text => 'debacle', :meaning => 'a sudden and violent collapse'},
          {:text => 'debauch', :meaning => 'a wild gathering involving excessive drinking and promiscuity'},
          {:text => 'debility', :meaning => 'the state of being weak in health or body (especially from old age)'},
          {:text => 'decadent', :meaning => 'marked by excessive self-indulgence and moral decay'},
          {:text => 'decentralization', :meaning => 'the social process in which population and industry moves from urban centers to outlying districts'},
          {:text => 'deciduous', :meaning => '(of plants and shrubs) shedding foliage at the end of the growing season'},
          {:text => 'deciphered', :meaning => 'converted from cryptic to intelligible language'},
          {:text => 'declamation', :meaning => 'vehement oratory'},
          {:text => 'defamation', :meaning => "a false accusation of an offense or a malicious misrepresentation of someone's words or actions"},
          {:text => 'defeasible', :meaning => 'capable of being annulled or voided or terminated'},
          {:text => 'defoliant', :meaning => 'a chemical that is sprayed on plants and causes their leaves to fall off'},
          {:text => 'delicatessen', :meaning => 'ready-to-eat food products'},
          {:text => 'delinquency', :meaning => 'nonpayment of a debt when due'},
          {:text => 'delouse', :meaning => 'free of lice'},
          {:text => 'demitasse', :meaning => 'small cup of strong black coffee without milk or cream'},
          {:text => 'demography', :meaning => 'the branch of sociology that studies the characteristics of human populations'},
          {:text => 'demolition', :meaning => 'an event (or the result of an event) that completely destroys something'},
          {:text => 'demurrage', :meaning => 'a charge required as compensation for the delay of a ship or freight car or other cargo beyond its scheduled time of departure'},
          {:text => 'denunciation', :meaning => 'a public act of denouncing'},
          {:text => 'dermatology', :meaning => 'the branch of medicine dealing with the skin and its diseases'},
          {:text => 'derogatory', :meaning => 'expressive of low opinion'},
          {:text => 'desensitize', :meaning => 'cause not to be sensitive'},
          {:text => 'despotism', :meaning => 'dominance through threat of punishment and violence'},
          {:text => 'destalinize', :meaning => 'counteract the effects and policies of Stalinism'},
          {:text => 'desuetude', :meaning => 'a state of inactivity or disuse'},
          {:text => 'desultory', :meaning => 'marked by lack of definite plan or regularity or purpose'},
          {:text => 'detergent', :meaning => 'having cleansing power'},
          {:text => 'deterrent', :meaning => 'tending to deter'},
          {:text => 'diacritical', :meaning => 'capable of distinguishing'},
          {:text => 'dialyzer', :meaning => 'a medical instrument for separating substances in solution by unequal diffusion through semipermeable membranes'},
          {:text => 'diaphanous', :meaning => 'so thin as to transmit light'},
          {:text => 'diaphragm', :meaning => 'a mechanical device in a camera that controls size of aperture of the lens'},
          {:text => 'diastole', :meaning => 'the widening of the chambers of the heart between two contractions when the chambers fill with blood'},
          {:text => 'diatribe', :meaning => 'thunderous verbal attack'},
          {:text => 'dichotomy', :meaning => 'being twofold'},
          {:text => 'didactic', :meaning => 'instructive (especially excessively)'},
          {:text => 'differential', :meaning => 'relating to or showing a difference'},
          {:text => 'diffident', :meaning => 'showing modest reserve'},
          {:text => 'dilatory', :meaning => 'wasting time'},
          {:text => 'diluvial', :meaning => 'of or connected with a deluge'},
          {:text => 'diminutive', :meaning => 'very small'},
          {:text => 'diphthong', :meaning => 'a vowel sound that starts near the articulatory position for one vowel and moves toward the position for another'},
          {:text => 'discountenance', :meaning => 'look with disfavor on'},
          {:text => 'disparate', :meaning => 'fundamentally different or distinct in quality or kind'},
          {:text => 'dissentient', :meaning => '(of Catholics) refusing to attend services of the Church of England'},
          {:text => 'dissertation', :meaning => 'a treatise advancing a new point of view resulting from research'},
          {:text => 'dissident', :meaning => 'characterized by departure from accepted beliefs or standards'},
          {:text => 'dissipated', :meaning => 'unrestrained by convention or morality'},
          {:text => 'dissonant', :meaning => 'characterized by musical dissonance'},
          {:text => 'dithyramb', :meaning => 'a wildly enthusiastic speech or piece of writing'},
          {:text => 'diverticulitis', :meaning => 'inflammation of a diverticulum in the digestive tract (especially the colon)'},
          {:text => 'dolomitic', :meaning => 'relating to or consisting of dolomite'},
          {:text => 'dolorous', :meaning => 'showing sorrow'},
          {:text => 'dossier', :meaning => "a collection of papers containing detailed information about a particular person or subject (usually a person's record)"},
          {:text => 'dowager', :meaning => 'a widow holding property received from her deceased husband'},
          {:text => 'dubonnet', :meaning => '(trademark) a sweet aromatic French wine (red or white) used chiefly as an aperitif'},
          {:text => 'ductile', :meaning => 'easily influenced'},
          {:text => 'dyscrasia', :meaning => 'an abnormal or physiologically unbalanced state of the body'},
          {:text => 'dysentery', :meaning => 'an infection of the intestines marked by severe diarrhea'},
          {:text => 'ebullition', :meaning => 'an unrestrained expression of emotion'},
          {:text => 'ecclesiastical', :meaning => 'of or associated with a church (especially a Christian Church)'},
          {:text => 'eclectic', :meaning => 'selecting what seems best of various styles or ideas n 1: someone who selects according to the eclectic method'},
          {:text => 'edelweiss', :meaning => 'alpine perennial plant native to Europe having leaves covered with whitish down and small flower heads held in stars of glistening whitish bracts'},
          {:text => 'effaceable', :meaning => 'capable of being effaced'},
          {:text => 'effeminacy', :meaning => 'the trait of being effeminate (derogatory of a man)'},
          {:text => 'egalitarian', :meaning => 'favoring social equality'},
          {:text => 'egocentric', :meaning => 'limited to or caring only about yourself and your own needs'},
          {:text => 'elasticity', :meaning => 'the tendency of a body to return to its original shape after it has been stretched or compressed'},
          {:text => 'electioneer', :meaning => 'work actively for a political candidate or a party'},
          {:text => 'electrocardiogram', :meaning => 'a graphical recording of the cardiac cycle produced by an electrocardiograph'},
          {:text => 'electrolysis', :meaning => '(chemistry) a chemical decomposition reaction produced by passing an electric current through a solution containing ions'},
          {:text => 'elitist', :meaning => 'someone who believes in rule by an elite group'},
          {:text => 'emaciation', :meaning => 'extreme leanness (usually caused by starvation or disease)'},
          {:text => 'emphysema', :meaning => 'an abnormal condition of the lungs marked by decreased respiratory function'},
          {:text => 'empyrean', :meaning => 'of or relating to the sky or heavens'},
          {:text => 'encephalitis', :meaning => 'inflammation of the brain usually caused by a virus'},
          {:text => 'encumbrance', :meaning => 'an onerous or difficult concern'},
          {:text => 'encyclical', :meaning => 'intended for wide distribution'},
          {:text => 'enervated', :meaning => 'lacking strength or vigor'},
          {:text => 'ensemble', :meaning => 'a group of musicians playing or singing together'},
          {:text => 'entente', :meaning => 'an informal alliance between countries'},
          {:text => 'entourage', :meaning => 'the group following and attending to some important person'},
          {:text => 'entrepreneurial', :meaning => 'of or relating to an entrepreneur'},
          {:text => 'enzymology', :meaning => 'the branch of biochemistry dealing with the chemical nature and biological activity of enzymes'},
          {:text => 'ephemeral', :meaning => 'lasting a very short time'},
          {:text => 'epicure', :meaning => 'a person devoted to refined sensuous enjoyment (especially good food and drink)'},
          {:text => 'epitome', :meaning => 'a standard or typical example'},
          {:text => 'epsilon', :meaning => 'the 5th letter of the Greek alphabet'},
          {:text => 'equatorial', :meaning => 'of or relating to or at an equator'},
          {:text => 'equerry', :meaning => 'an official charged with the care of the horses of princes or nobles'},
          {:text => 'equivocate', :meaning => 'be deliberately ambiguous or unclear in order to mislead or withhold information'},
          {:text => 'erysipelas', :meaning => 'an acute streptococcal infection characterized by deep-red inflammation of the skin and mucous membranes'},
          {:text => 'escargot', :meaning => 'edible terrestrial snail usually served in the shell with a sauce of melted butter and garlic'},
          {:text => 'escheat', :meaning => 'a reversion to the state (as the ultimate owner of property) in the absence of legal heirs'},
          {:text => 'esoteric', :meaning => 'confined to and understandable by only an enlightened inner circle'},
          {:text => 'espalier', :meaning => 'a trellis on which ornamental shrub or fruit tree is trained to grow flat'},
          {:text => 'espousal', :meaning => 'archaic terms for a wedding or wedding feast'},
          {:text => 'etiolation', :meaning => 'a pale and sickly appearance'},
          {:text => 'etymology', :meaning => 'a history of a word'},
          {:text => 'eucalyptus', :meaning => 'wood of any of various eucalyptus trees valued as timber'},
          {:text => 'euphemism', :meaning => 'an inoffensive or indirect expression that is substituted for one that is considered offensive or too harsh'},
          {:text => 'euphony', :meaning => 'any agreeable (pleasing and harmonious) sounds'},
          {:text => 'euthanasia', :meaning => 'the act of killing someone painlessly (especially someone suffering from an incurable illness)'},
          {:text => 'evanescent', :meaning => 'tending to vanish like vapor'},
          {:text => 'eviscerate', :meaning => 'having been disembowelled v 1: surgically remove a part of a structure or an organ'},
          {:text => 'excoriate', :meaning => 'express strong disapproval of'},
          {:text => 'exculpate', :meaning => 'pronounce not guilty of criminal charges'},
          {:text => 'exigency', :meaning => 'a pressing or urgent situation'},
          {:text => 'exorcism', :meaning => 'freeing from evil spirits'},
          {:text => 'expatriate', :meaning => 'a person who is voluntarily absent from home or country'},
          {:text => 'expeditious', :meaning => 'marked by speed and efficiency'},
          {:text => 'extempore', :meaning => 'without prior preparation'},
          {:text => 'extraneous', :meaning => 'not pertinent to the matter under consideration'},
          {:text => 'extricate', :meaning => 'release from entanglement of difficulty'},
          {:text => 'facetious', :meaning => 'cleverly amusing in tone'},
          {:text => 'factitious', :meaning => 'not produced by natural forces'},
          {:text => 'falsetto', :meaning => 'artificially high'},
          {:text => 'falsification', :meaning => 'any evidence that helps to establish the falsity of something'},
          {:text => 'farrago', :meaning => 'a motley assortment of things'},
          {:text => 'fascism', :meaning => 'a political theory advocating an authoritarian hierarchical government (as opposed to democracy or liberalism)'},
          {:text => 'featherbedding', :meaning => 'the practice (usually by a labor union) of requiring an employer to hire more workers than are required'},
          {:text => 'feckless', :meaning => 'not fit to assume responsibility'},
          {:text => 'figurine', :meaning => 'a small carved or molded figure'},
          {:text => 'filbert', :meaning => 'small nut-bearing tree much grown in Europe'},
          {:text => 'finesse', :meaning => 'subtly skillful handling of a situation'},
          {:text => 'fissure', :meaning => 'a long narrow depression in a surface'},
          {:text => 'flammable', :meaning => 'easily ignited'},
          {:text => 'flotsam', :meaning => 'the floating wreckage of a ship'},
          {:text => 'follicle', :meaning => 'any small spherical group of cells containing a cavity'},
          {:text => 'footslogger', :meaning => 'fights on foot with small arms'},
          {:text => 'forager', :meaning => 'someone who hunts for food and provisions'},
          {:text => 'forceps', :meaning => 'an extractor consisting of a pair of pincers used in medical treatment (especially for the delivery of babies)'},
          {:text => 'forfeiture', :meaning => 'something that is lost or surrendered as a penalty'},
          {:text => 'fortnightly', :meaning => 'every two weeks'},
          {:text => 'fortuitous', :meaning => 'having no cause or apparent cause'},
          {:text => 'freebooter', :meaning => 'someone who takes spoils or plunder (as in war)'},
          {:text => 'freewheeler', :meaning => 'someone acting freely or even irresponsibly'},
          {:text => 'fricassee', :meaning => 'pieces of chicken or other meat stewed in gravy with e.g. carrots and onions and served with noodles or dumplings v 1: make a fricassee of by cooking'},
          {:text => 'frigate', :meaning => 'a medium size square-rigged warship of the 18th and 19th centuries'},
          {:text => 'frolicsome', :meaning => 'given to merry frolicking'},
          {:text => 'galleon', :meaning => 'a large square-rigged sailing ship with three or more masts'},
          {:text => 'gambrel', :meaning => 'a gable roof with two slopes on each side and the lower slope being steeper'},
          {:text => 'gentian', :meaning => 'any of various plants of the family Gentianaceae especially the genera Gentiana and Gentianella and Gentianopsis'},
          {:text => 'geodesy', :meaning => 'the branch of geology that studies the shape of the earth and the determination of the exact position of geographical points'},
          {:text => 'geriatrics', :meaning => 'the branch of medical science that deals with diseases and problems specific to old people'},
          {:text => 'germicidal', :meaning => 'preventing infection by inhibiting the growth or action of microorganisms'},
          {:text => 'glabrous', :meaning => 'having no hair or similar growth'},
          {:text => 'glaucoma', :meaning => 'an eye disease that damages the optic nerve and impairs vision (sometimes progressing to blindness)'},
          {:text => 'gossamer', :meaning => 'characterized by unusual lightness and delicacy'},
          {:text => 'gossipy', :meaning => 'prone to friendly informal communication'},
          {:text => 'gracile', :meaning => 'slender and graceful'},
          {:text => 'granary', :meaning => 'a storehouse for threshed grain or animal feed'},
          {:text => 'grandeur', :meaning => 'the quality of being magnificent or splendid or grand'},
          {:text => 'grandiose', :meaning => 'impressive because of unnecessary largeness or grandeur'},
          {:text => 'granule', :meaning => 'a tiny grain'},
          {:text => 'grievous', :meaning => 'causing fear or anxiety by threatening great harm'},
          {:text => 'grimace', :meaning => 'a contorted facial expression'},
          {:text => 'gustatory', :meaning => 'of or relating to gustation'},
          {:text => 'gyroscopic', :meaning => 'having the characteristics of a gyroscope'},
          {:text => 'halftone', :meaning => 'a print obtained from photoengraving'},
          {:text => 'harangue', :meaning => 'a loud bombastic declamation expressed with strong emotion'},
          {:text => 'haricot', :meaning => 'a French variety of green bean plant bearing light-colored beans'},
          {:text => 'hemophilia', :meaning => 'congenital tendency to uncontrolled bleeding'},
          {:text => 'hemorrhoid', :meaning => 'pain caused by venous swelling at or inside the anal sphincter'},
          {:text => 'hepatitis', :meaning => 'inflammation of the liver caused by a virus or a toxin'},
          {:text => 'herbicide', :meaning => 'a chemical agent that destroys plants or inhibits their growth'},
          {:text => 'hermetically', :meaning => 'in an airtight manner'},
          {:text => 'hermitage', :meaning => 'the abode of a hermit'},
          {:text => 'hirsute', :meaning => 'having or covered with hair'},
          {:text => 'histiocyte', :meaning => 'a macrophage that is found in connective tissue'},
          {:text => 'holocaust', :meaning => 'an act of mass destruction and loss of life (especially in war or by fire)'},
          {:text => 'homogenized', :meaning => 'formed by blending unlike elements especially by reducing one element to particles and dispersing them throughout another substance'},
          {:text => 'homophonous', :meaning => 'characteristic of the phenomenon of words of different origins that are pronounced the same way'},
          {:text => 'horrendous', :meaning => 'causing fear or dread or terror'},
          {:text => 'horripilation', :meaning => 'reflex erection of hairs of the skin in response to cold or emotional stress or skin irritation'},
          {:text => 'hydraulic', :meaning => 'moved or operated or effected by liquid (water or oil)'},
          {:text => 'hyperbole', :meaning => 'extravagant exaggeration'},
          {:text => 'hypochondriac', :meaning => 'suffering from hypochondria'},
          {:text => 'hypsography', :meaning => "the scientific study of the earth's configuration above sea level (emphasizing the measurement of land altitudes relative to sea level)"},
          {:text => 'ichthyology', :meaning => 'the branch of zoology that studies fishes'},
          {:text => 'iconoclast', :meaning => 'a destroyer of images used in religious worship'},
          {:text => 'ideogram', :meaning => 'a graphic character that indicates the meaning of a thing without indicating the sounds used to say it'},
          {:text => 'idiomatic', :meaning => 'of or relating to or conforming to idiom'},
          {:text => 'idolatry', :meaning => 'religious zeal'},
          {:text => 'idyllic', :meaning => 'excellent and delightful in all respects'},
          {:text => 'ignominy', :meaning => 'a state of dishonor'},
          {:text => 'ignoramus', :meaning => 'an ignorant person'},
          {:text => 'illegitimate', :meaning => 'contrary to or forbidden by law'},
          {:text => 'imbecile', :meaning => 'having a mental age of three to seven years'},
          {:text => 'imbibition', :meaning => '(chemistry) the absorption of a liquid by a solid or gel'},
          {:text => 'imbricate', :meaning => 'used especially of leaves or bracts'},
          {:text => 'imitative', :meaning => 'marked by or given to imitation'},
          {:text => 'immersion', :meaning => 'sinking until covered completely with water'},
          {:text => 'immolate', :meaning => 'offer as a sacrifice by killing or by giving up to destruction'},
          {:text => 'immunize', :meaning => 'law: grant immunity from prosecution'},
          {:text => 'immutable', :meaning => 'not subject or susceptible to change or variation in form or quality or nature'},
          {:text => 'impalpable', :meaning => 'incapable of being perceived by the senses especially the sense of touch'},
          {:text => 'impasse', :meaning => 'a situation in which no progress can be made or no advancement is possible'},
          {:text => 'impeccable', :meaning => 'without fault or error'},
          {:text => 'impecunious', :meaning => 'not having enough money to pay for necessities'},
          {:text => 'impedimenta', :meaning => 'any structure that makes progress difficult'},
          {:text => 'impinge', :meaning => 'impinge or infringe upon'},
          {:text => 'impishness', :meaning => 'the trait of behaving like an imp'},
          {:text => 'implacable', :meaning => 'incapable of being placated'},
          {:text => 'importune', :meaning => 'beg persistently and urgently'},
          {:text => 'imprimatur', :meaning => 'formal and explicit approval'},
          {:text => 'impropriety', :meaning => 'an improper demeanor'},
          {:text => 'impunity', :meaning => 'exemption from punishment or loss'},
          {:text => 'inanity', :meaning => 'total lack of meaning or ideas'},
          {:text => 'incendiary', :meaning => 'involving deliberate burning of property'},
          {:text => 'inchoate', :meaning => 'only partly in existence'},
          {:text => 'incipient', :meaning => 'only partly in existence'},
          {:text => 'incision', :meaning => 'a depression scratched or carved into a surface'},
          {:text => 'inclemency', :meaning => 'weather unsuitable for outdoor activities'},
          {:text => 'incoherence', :meaning => 'lack of cohesion or clarity or organization'},
          {:text => 'incommutable', :meaning => 'not subject to alteration or change'},
          {:text => 'incomprehensible', :meaning => 'incapable of being explained or accounted for'},
          {:text => 'incorrigible', :meaning => 'impervious to correction by punishment'},
          {:text => 'incursive', :meaning => 'involving invasion or aggressive attack'},
          {:text => 'indefeasible', :meaning => 'not liable to being annulled or voided or undone'},
          {:text => 'indelibly', :meaning => 'in an indelible manner'},
          {:text => 'indemnity', :meaning => 'protection against future loss'},
          {:text => 'indictment', :meaning => 'a formal document written for a prosecuting attorney charging a person with some offense'},
          {:text => 'indigenous', :meaning => 'originating where it is found'},
          {:text => 'indubitable', :meaning => 'too obvious to be doubted'},
          {:text => 'ineffable', :meaning => 'defying expression or description'},
          {:text => 'ineligibility', :meaning => 'the quality or state of being ineligible'},
          {:text => 'ineradicable', :meaning => 'not able to be destroyed or rooted out'},
          {:text => 'inexorable', :meaning => 'not to be placated or appeased or moved by entreaty'},
          {:text => 'infatuation', :meaning => 'a foolish and usually extravagant passion or love or admiration'},
          {:text => 'infinitesimal', :meaning => 'infinitely or immeasurably small'},
          {:text => 'infrared', :meaning => 'having or employing wavelengths longer than light but shorter than radio waves'},
          {:text => 'ingenuous', :meaning => 'characterized by an inability to mask your feelings'},
          {:text => 'ingratiate', :meaning => 'gain favor with somebody by deliberate efforts'},
          {:text => 'inimical', :meaning => 'not friendly'},
          {:text => 'iniquitous', :meaning => 'characterized by iniquity'},
          {:text => 'injurious', :meaning => 'harmful to living things'},
          {:text => 'innocuous', :meaning => 'not injurious to physical or mental health'},
          {:text => 'insatiable', :meaning => 'impossible to satisfy'},
          {:text => 'inscrutable', :meaning => 'of an obscure nature'},
          {:text => 'insomniac', :meaning => 'experiencing or accompanied by sleeplessness'},
          {:text => 'insouciance', :meaning => 'the cheerful feeling you have when nothing is troubling you'},
          {:text => 'insulin', :meaning => 'hormone secreted by the isles of Langerhans in the pancreas'},
          {:text => 'insurgent', :meaning => 'in opposition to a civil authority or government'},
          {:text => 'intercom', :meaning => 'a communication system linking different rooms within a building or ship etc'},
          {:text => 'interlocutor', :meaning => 'the performer in the middle of a minstrel line who engages the others in talk'},
          {:text => 'interloper', :meaning => 'someone who intrudes on the privacy or property of another without permission'},
          {:text => 'intermezzo', :meaning => 'a short movement coming between the major sections of a symphony'},
          {:text => 'interminable', :meaning => 'tiresomely long'},
          {:text => 'internecine', :meaning => '(of conflict) within a group or organization'},
          {:text => 'interregnum', :meaning => 'the time between two reigns, governments, etc.'},
          {:text => 'interrogatory', :meaning => 'relating to the use of or having the nature of an interrogation'},
          {:text => 'intrinsic', :meaning => 'belonging to a thing by its very nature'},
          {:text => 'intussusception', :meaning => 'the folding in of an outer layer so as to form a pocket in the surface'},
          {:text => 'inunction', :meaning => 'anointing as part of a religious ceremony or healing ritual'},
          {:text => 'inundate', :meaning => 'fill quickly beyond capacity'},
          {:text => 'invidious', :meaning => 'containing or implying a slight or showing prejudice'},
          {:text => 'irascible', :meaning => 'quickly aroused to anger'},
          {:text => 'irreconcilable', :meaning => 'impossible to reconcile'},
          {:text => 'irreducible', :meaning => 'incapable of being made smaller or simpler'},
          {:text => 'irremediable', :meaning => 'impossible to remedy or correct or redress'},
          {:text => 'irretrievably', :meaning => 'in an irretrievable manner'},
          {:text => 'isosceles', :meaning => '(of a triangle) having two sides of equal length'},
          {:text => 'isothermal', :meaning => 'of a process or change taking place at constant temperature'},
          {:text => 'itinerary', :meaning => 'an established line of travel or access'},
          {:text => 'jamboree', :meaning => 'a gay festivity'},
          {:text => 'jejunum', :meaning => 'the part of the small intestine between the duodenum and the ileum'},
          {:text => 'jeremiad', :meaning => 'a long and mournful complaint'},
          {:text => 'jingoism', :meaning => 'an appeal intended to arouse patriotic emotions'},
          {:text => 'jocosity', :meaning => 'fun characterized by humor'},
          {:text => 'jollity', :meaning => 'feeling jolly and jovial and full of good humor'},
          {:text => 'journalism', :meaning => 'newspapers and magazines collectively'},
          {:text => 'jubilation', :meaning => 'a feeling of extreme joy'},
          {:text => 'judiciary', :meaning => 'persons who administer justice'},
          {:text => 'juxtaposition', :meaning => 'the act of positioning close together (or side by side)'},
          {:text => 'kaleidoscope', :meaning => 'a complex pattern of constantly changing colors and shapes'},
          {:text => 'kamikaze', :meaning => 'a fighter plane used for suicide missions by Japanese pilots in World War II'},
          {:text => 'klavern', :meaning => 'a local unit of the Ku Klux Klan'},
          {:text => 'labyrinth', :meaning => 'complex system of paths or tunnels in which it is easy to get lost'},
          {:text => 'laceration', :meaning => 'a torn ragged wound'},
          {:text => 'lachrymose', :meaning => 'showing sorrow'},
          {:text => 'lactose', :meaning => 'a sugar comprising one glucose molecule linked to a galactose molecule'},
          {:text => 'lagniappe', :meaning => 'a small gift (especially one given by a merchant to a customer who makes a purchase)'},
          {:text => 'lallation', :meaning => "defective articulation of the `l' phoneme or the phoneme `r' is pronounced as `l'"},
          {:text => 'landlubber', :meaning => 'a person who lives and works on land'},
          {:text => 'larcenous', :meaning => 'having a disposition to steal'},
          {:text => 'latrine', :meaning => 'a public toilet in a military area'},
          {:text => 'laureate', :meaning => 'worthy of the greatest honor or distinction'},
          {:text => 'layette', :meaning => 'kit consisting of a complete outfit (clothing and accessories) for a new baby'},
          {:text => 'lebensraum', :meaning => 'space sought for occupation by a nation whose population is expanding'},
          {:text => 'lethargic', :meaning => 'deficient in alertness or activity'},
          {:text => 'lieutenancy', :meaning => 'the position of a lieutenant'},
          {:text => 'ligustrum', :meaning => 'genus of Old World shrubs: privet'},
          {:text => 'lilliputian', :meaning => 'tiny'},
          {:text => 'lingerie', :meaning => "women's underwear and nightclothes"},
          {:text => 'litigious', :meaning => 'of or relating to litigation'},
          {:text => 'lobotomy', :meaning => 'surgical interruption of nerve tracts to and from the frontal lobe of the brain'},
          {:text => 'logistician', :meaning => 'a person skilled at symbolic logic'},
          {:text => 'lucidity', :meaning => 'free from obscurity and easy to understand'},
          {:text => 'lucrative', :meaning => 'producing a sizeable profit'},
          {:text => 'lugubrious', :meaning => 'excessively mournful'},
          {:text => 'luxuriant', :meaning => 'marked by complexity and richness of detail'},
          {:text => 'macrame', :meaning => 'a relatively coarse lace'},
          {:text => 'macrobiotics', :meaning => 'the theory of promoting health and longevity by means of diet (especially whole beans and grains)'},
          {:text => 'mademoiselle', :meaning => 'small silvery drumfish often mistaken for white perch'},
          {:text => 'magneto', :meaning => 'a small dynamo with a secondary winding that produces a high voltage enabling a spark to jump between the poles of a spark plug in a gasoline engine'},
          {:text => 'magnificence', :meaning => 'splendid or imposing in size or appearance'},
          {:text => 'maladroit', :meaning => 'not adroit'},
          {:text => 'mammalia', :meaning => 'warm-blooded vertebrates characterized by mammary glands in the female'},
          {:text => 'mandamus', :meaning => "an extraordinary writ commanding an official to perform a ministerial act that the law recognizes as an absolute duty and not a matter for the official's discretion"},
          {:text => 'manicurist', :meaning => 'a beautician who cleans and trims and polishes the fingernails'},
          {:text => 'maraschino', :meaning => 'distilled from fermented juice of bitter wild marasca cherries'},
          {:text => 'marsupial', :meaning => 'of or relating to the marsupials'},
          {:text => 'masseuse', :meaning => 'a female massager'},
          {:text => 'matriarchal', :meaning => 'characteristic of a matriarchy'},
          {:text => 'matriculation', :meaning => 'admission to a group (especially a college or university)'},
          {:text => 'measurable', :meaning => 'capable of being measured'},
          {:text => 'meerschaum', :meaning => 'a white clayey mineral'},
          {:text => 'melancholia', :meaning => 'extreme depression characterized by tearful sadness and irrational fears'},
          {:text => 'mellifluous', :meaning => 'pleasing to the ear'},
          {:text => 'memorabilia', :meaning => 'a record of things worth remembering'},
          {:text => 'mendacious', :meaning => 'given to lying'},
          {:text => 'mephitic', :meaning => 'of noxious stench from atmospheric pollution'},
          {:text => 'metallurgical', :meaning => 'of or relating to metallurgy'},
          {:text => 'metamorphosis', :meaning => 'the marked and rapid transformation of a larva into an adult that occurs in some animals'},
          {:text => 'metricize', :meaning => 'express in the metric system'},
          {:text => 'microcosm', :meaning => 'a miniature model of something'},
          {:text => 'millennium', :meaning => 'a span of 1000 years'},
          {:text => 'miniature', :meaning => 'being on a very small scale'},
          {:text => 'misanthropic', :meaning => 'believing the worst of human nature and motives'},
          {:text => 'misdemeanor', :meaning => 'a crime less serious than a felony'},
          {:text => 'misogyny', :meaning => 'hatred of women'},
          {:text => 'mnemonic', :meaning => 'of or relating to or involved the practice of aiding the memory'},
          {:text => 'monogamy', :meaning => 'having only one spouse at a time'},
          {:text => 'monolith', :meaning => 'a single great stone (often in the form of a column or obelisk)'},
          {:text => 'monotony', :meaning => 'the quality of wearisome constancy, routine, and lack of variety'},
          {:text => 'monsieur', :meaning => 'used as a French courtesy title'},
          {:text => 'nauseate', :meaning => 'upset and make nauseated'},
          {:text => 'nefarious', :meaning => 'extremely wicked'},
          {:text => 'negligence', :meaning => 'failure to act with the prudence that a reasonable person would exercise under the same circumstances'},
          {:text => 'neoplasm', :meaning => 'an abnormal new mass of tissue that serves no purpose'},
          {:text => 'nescience', :meaning => 'ignorance (especially of orthodox beliefs)'},
          {:text => 'neurotic', :meaning => 'characteristic of or affected by neurosis'},
          {:text => 'niggardly', :meaning => 'petty or reluctant in giving or spending'},
          {:text => 'nomenclature', :meaning => 'a system of words used to name things in a particular discipline'},
          {:text => 'nonagenarian', :meaning => 'being from 90 to 99 years old'},
          {:text => 'obdurate', :meaning => 'stubbornly persistent in wrongdoing'},
          {:text => 'obeisance', :meaning => 'bending the head or body or knee as a sign of reverence or submission or shame or greeting'},
          {:text => 'oblique', :meaning => 'slanting or inclined in direction or course or position-- neither parallel nor perpendicular nor right-angled'},
          {:text => 'oblivion', :meaning => 'the state of being disregarded or forgotten'},
          {:text => 'obloquy', :meaning => 'state of disgrace resulting from public abuse'},
          {:text => 'obstetrics', :meaning => 'the branch of medicine dealing with childbirth and care of the mother'},
          {:text => 'obviate', :meaning => 'do away with'},
          {:text => 'occidental', :meaning => 'denoting or characteristic of countries of Europe and the western hemisphere'},
          {:text => 'odometer', :meaning => 'a meter that shows mileage traversed'},
          {:text => 'odoriferous', :meaning => 'morally offensive'},
          {:text => 'odyssey', :meaning => 'a long wandering and eventful journey'},
          {:text => 'officiousness', :meaning => 'aggressiveness as evidenced by intruding'},
          {:text => 'omniscience', :meaning => 'the state of being omniscient'},
          {:text => 'omnivorous', :meaning => 'feeding on both plants and animals'},
          {:text => 'opalescent', :meaning => 'having a play of lustrous rainbow colors'},
          {:text => 'ophthalmic', :meaning => 'of or relating to the eye'},
          {:text => 'opprobrious', :meaning => 'expressing offensive reproach'},
          {:text => 'organza', :meaning => 'a fabric made of silk or a silklike fabric that resembles organdy'},
          {:text => 'orthoepist', :meaning => 'a practitioner of orthoepy (especially one of the 17th or 18th century scholars who proposed to reform English spelling so it would reflect pronunciation more closely)'},
          {:text => 'oscillation', :meaning => 'the process of oscillating between states'},
          {:text => 'ostentatiously', :meaning => 'with ostentation'},
          {:text => 'pachyderm', :meaning => 'any of various nonruminant hoofed mammals having very thick skin: elephant'},
          {:text => 'palatable', :meaning => 'acceptable to the taste or mind'},
          {:text => 'palaver', :meaning => 'flattery intended to persuade'},
          {:text => 'palpitation', :meaning => 'a rapid and irregular heart beat'},
          {:text => 'panacea', :meaning => '(Greek mythology) the goddess of healing'},
          {:text => 'panegyric', :meaning => 'formally expressing praise'},
          {:text => 'panoplied', :meaning => 'equipped with the complete arms and armor of a warrior'},
          {:text => 'panoramic', :meaning => 'as from an altitude or distance'},
          {:text => 'paranoia', :meaning => 'a psychological disorder characterized by delusions of persecution or grandeur'},
          {:text => 'paraphernalia', :meaning => 'equipment consisting of miscellaneous articles needed for a particular operation or sport etc.'},
          {:text => 'parasol', :meaning => 'a handheld collapsible source of shade'},
          {:text => 'paroxysm', :meaning => 'a sudden uncontrollable attack'},
          {:text => 'parquet', :meaning => 'a floor made of parquetry'},
          {:text => 'parsnip', :meaning => 'the whitish root of cultivated parsnip'},
          {:text => 'pathology', :meaning => 'the branch of medical science that studies the causes and nature and effects of diseases'},
          {:text => 'paucity', :meaning => 'an insufficient quantity or number'},
          {:text => 'pavilion', :meaning => 'large and often sumptuous tent'},
          {:text => 'peccadillo', :meaning => 'a petty misdeed'},
          {:text => 'pecuniary', :meaning => 'relating to or involving money'},
          {:text => 'pedagogy', :meaning => 'the principles and methods of instruction'},
          {:text => 'pedodontist', :meaning => "a dentist who specializes in the care of children's teeth"},
          {:text => 'pellagra', :meaning => 'a disease caused by deficiency of niacin or tryptophan (or by a defect in the metabolic conversion of tryptophan to niacin)'},
          {:text => 'percipient', :meaning => 'characterized by ease and quickness in perceiving'},
          {:text => 'peregrinate', :meaning => 'travel around, through, or over, especially on foot'},
          {:text => 'peremptory', :meaning => 'offensively self-assured or given to exercising usually unwarranted power'},
          {:text => 'perfidious', :meaning => 'tending to betray'},
          {:text => 'periphery', :meaning => 'the outside boundary or surface of something'},
          {:text => 'periphrasis', :meaning => 'a style that involves indirect ways of expressing things'},
          {:text => 'permeable', :meaning => 'allowing fluids or gases to pass or diffuse through'},
          {:text => 'perpetuity', :meaning => 'the property of being perpetual (seemingly ceaseless)'},
          {:text => 'perspicacious', :meaning => 'acutely insightful and wise'},
          {:text => 'perturbation', :meaning => 'an unhappy and worried mental state'},
          {:text => 'pestiferous', :meaning => 'contaminated with infecting organisms'},
          {:text => 'petticoat', :meaning => 'undergarment worn under a skirt'},
          {:text => 'petunia', :meaning => 'any of numerous tropical herbs having fluted funnel-shaped flowers'},
          {:text => 'phalanx', :meaning => 'any of the bones of the fingers or toes'},
          {:text => 'philology', :meaning => 'the humanistic study of language and literature'},
          {:text => 'phlegmatic', :meaning => 'showing little emotion'},
          {:text => 'photomontage', :meaning => 'a montage that uses photographic images'},
          {:text => 'photosynthesis', :meaning => 'synthesis of compounds with the aid of radiant energy (especially in plants)'},
          {:text => 'phraseology', :meaning => 'the manner in which something is expressed in words'},
          {:text => 'physicist', :meaning => 'a scientist trained in physics'},
          {:text => 'picaresque', :meaning => 'involving clever rogues or adventurers especially as in a type of fiction'},
          {:text => 'picayune', :meaning => '(informal) small and of little importance'},
          {:text => 'piccalilli', :meaning => 'relish of chopped pickled cucumbers and green peppers and onion'},
          {:text => 'piquancy', :meaning => 'a tart spicy quality'},
          {:text => 'pirouette', :meaning => '(ballet) a rapid spin of the body (especially on the toes as in ballet) v 1: do a pirouette, usually as part of a dance'},
          {:text => 'piscatorial', :meaning => 'relating to or characteristic of the activity of fishing'},
          {:text => 'placable', :meaning => 'easily calmed or pacified'},
          {:text => 'placatory', :meaning => 'intended to pacify by acceding to demands or granting concessions'},
          {:text => 'plagiarism', :meaning => 'a piece of writing that has been copied from someone else and is presented as being your own work'},
          {:text => 'plenipotentiary', :meaning => 'a diplomat who is fully authorized to represent his or her government'},
          {:text => 'poignant', :meaning => 'arousing affect'},
          {:text => 'poliomyelitis', :meaning => 'an acute viral disease marked by inflammation of nerve cells of the brain stem and spinal cord'},
          {:text => 'polysyllabic', :meaning => 'having or characterized by words of more than three syllables'},
          {:text => 'pontifical', :meaning => 'proceeding from or ordered by or subject to a pope or the papacy regarded as the successor of the Apostles'},
          {:text => 'posthumous', :meaning => "occurring or coming into existence after a person's death"},
          {:text => 'potassium', :meaning => 'a light soft silver-white metallic element of the alkali metal group'},
          {:text => 'precocious', :meaning => 'characterized by or characteristic of exceptionally early development or maturity (especially in mental aptitude)'},
          {:text => 'precursory', :meaning => 'warning of future misfortune'},
          {:text => 'predecessor', :meaning => 'one who precedes you in time (as in holding a position or office)'},
          {:text => 'prestidigitator', :meaning => 'someone who performs magic tricks to amuse an audience'},
          {:text => 'probabilism', :meaning => 'a Roman Catholic system of casuistry that when expert opinions differ an actor can follow any solidly probable opinion that he wishes even though some different opinion might be more probable'},
          {:text => 'proboscis', :meaning => 'the human nose (especially when it is large)'},
          {:text => 'procrustean', :meaning => 'of or relating to the mythical giant Procrustes or the mode of torture practiced by him'},
          {:text => 'prodigal', :meaning => 'recklessly wasteful'},
          {:text => 'profligacy', :meaning => 'the trait of spending extravagantly'},
          {:text => 'progeny', :meaning => 'the immediate descendants of a person'},
          {:text => 'prognostication', :meaning => 'a sign of something about to happen'},
          {:text => 'proliferation', :meaning => 'growth by the rapid multiplication of parts'},
          {:text => 'promulgate', :meaning => 'state or announce'},
          {:text => 'propinquity', :meaning => 'the property of being close together'},
          {:text => 'propitiate', :meaning => 'make peace with'},
          {:text => 'proscenium', :meaning => 'the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain)'},
          {:text => 'protocol', :meaning => '(computer science) rules determining the format and transmission of data'},
          {:text => 'psilophyton', :meaning => 'any plant or fossil of the genus Psilophyton'},
          {:text => 'psoriasis', :meaning => 'a chronic skin disease characterized by dry red patches covered with scales'},
          {:text => 'puerile', :meaning => 'of or characteristic of a child'},
          {:text => 'pugilistic', :meaning => 'of or relating to pugilism or pugilists'},
          {:text => 'puissance', :meaning => 'power to influence or coerce'},
          {:text => 'punctilious', :meaning => 'marked by precise accordance with details'},
          {:text => 'purgatory', :meaning => 'a temporary condition of torment or suffering'},
          {:text => 'purloin', :meaning => 'make off with belongings of others'},
          {:text => 'purveyor', :meaning => 'someone who supplies provisions (especially food)'},
          {:text => 'pusillanimous', :meaning => 'lacking in courage and manly strength and resolution'},
          {:text => 'putrescent', :meaning => 'becoming putrid'},
          {:text => 'pylorus', :meaning => 'a small circular opening between the stomach and the duodenum'},
          {:text => 'pyrrhic', :meaning => 'of or relating to a war dance of ancient Greece'},
          {:text => 'quagmire', :meaning => 'a soft wet area of low-lying land that sinks underfoot'},
          {:text => 'quarantine', :meaning => 'enforced isolation of patients suffering from a contagious disease in order to prevent the spread of disease'},
          {:text => 'quiescent', :meaning => 'not active or activated'},
          {:text => 'quintessence', :meaning => 'the fifth and highest element after air and earth and fire and water'},
          {:text => 'quixotic', :meaning => 'not sensible about practical matters'},
          {:text => 'rallentando', :meaning => 'slowing down'},
          {:text => 'rancorous', :meaning => 'showing deep-seated resentment'},
          {:text => 'rathskeller', :meaning => 'a tavern below street level featuring beer'},
          {:text => 'ratiocination', :meaning => 'the proposition arrived at by logical reasoning (such as the proposition that must follow from the major and minor premises of a syllogism)'},
          {:text => 'raucous', :meaning => 'unpleasantly loud and harsh'},
          {:text => 'recalcitrant', :meaning => 'stubbornly resistant to authority or control'},
          {:text => 'recognizance', :meaning => '(law) a security entered into before a court with a condition to perform some act required by law'},
          {:text => 'recrudescence', :meaning => 'a return of something after a period of abatement'},
          {:text => 'redoubtable', :meaning => 'inspiring fear'},
          {:text => 'redundancy', :meaning => 'repetition of messages to reduce the probability of errors in transmission'},
          {:text => 'regimen', :meaning => '(medicine) a systematic plan for therapy (often including diet)'},
          {:text => 'rehabilitation', :meaning => 'the restoration of someone to a useful place in society'},
          {:text => 'reiterate', :meaning => 'to say, state, or perform again'},
          {:text => 'remuneration', :meaning => 'something that remunerates'},
          {:text => 'renaissance', :meaning => 'the period of European history at the close of the Middle Ages and the rise of the modern world'},
          {:text => 'repatriation', :meaning => 'the act of returning to the country of origin'},
          {:text => 'repercussion', :meaning => 'a remote or indirect consequence of some action'},
          {:text => 'repertoire', :meaning => 'the entire range of skills or aptitudes or devices used in a particular field or occupation'},
          {:text => 'reprehensible', :meaning => 'bringing or deserving severe rebuke or censure'},
          {:text => 'reptilian', :meaning => 'of or relating to the class Reptilia n 1: any cold-blooded vertebrate of the class Reptilia including tortoises, turtles, snakes, lizards, alligators, crocodiles, and extinct forms'},
          {:text => 'rescind', :meaning => 'cancel officially'},
          {:text => 'resilient', :meaning => 'recovering readily from adversity, depression, or the like'},
          {:text => 'resuscitate', :meaning => 'cause to regain consciousness'},
          {:text => 'retaliatory', :meaning => 'of or relating to or having the nature of retribution'},
          {:text => 'reticence', :meaning => 'the trait of being uncommunicative'},
          {:text => 'reveille', :meaning => '(military) signal to wake up'},
          {:text => 'rhetoric', :meaning => 'using language effectively to please or persuade'},
          {:text => 'rhododendron', :meaning => 'any shrub of the genus Rhododendron: evergreen shrubs or small shrubby trees having leathery leaves and showy clusters of campanulate (bell-shaped) flowers'},
          {:text => 'ricketiness', :meaning => 'the quality of not being steady or securely fixed in place'},
          {:text => 'riparian', :meaning => 'of or relating to or located on the banks of a river or stream'},
          {:text => 'rissole', :meaning => 'minced cooked meat or fish coated in egg and breadcrumbs and fried in deep fat'},
          {:text => 'roguery', :meaning => 'reckless or malicious behavior that causes discomfort or annoyance in others'},
          {:text => 'romanticism', :meaning => 'impractical romantic ideals and attitudes'},
          {:text => 'roughhewn', :meaning => 'of stone or timber'},
          {:text => 'roulette', :meaning => 'a line generated by a point on one figure rolling around a second figure'},
          {:text => 'roustabout', :meaning => "a member of a ship's crew who performs manual labor "},
          {:text => 'rubella', :meaning => 'a contagious viral disease that is a milder form of measles lasting three or four days'},
          {:text => 'sabbatical', :meaning => 'of or relating to the Sabbath'},
          {:text => 'saccharine', :meaning => 'overly sweet'},
          {:text => 'salicylate', :meaning => 'a salt of salicylic acid (included in several commonly used drugs)'},
          {:text => 'salivary', :meaning => 'of or relating to saliva'},
          {:text => 'sanctimonious', :meaning => 'excessively or hypocritically pious'},
          {:text => 'sanctity', :meaning => 'the quality of being holy'},
          {:text => 'sanguinary', :meaning => 'accompanied by bloodshed'},
          {:text => 'saprobic', :meaning => 'living in or being an environment rich in organic matter but lacking oxygen'},
          {:text => 'saprophagous', :meaning => '(of certain animals) feeding on dead or decaying animal matter'},
          {:text => 'sardonic', :meaning => 'disdainfully or ironically humorous'},
          {:text => 'satiate', :meaning => 'supplied (especially fed) to satisfaction'},
          {:text => 'satiety', :meaning => 'the state of being satisfactorily full and unable to take on more'},
          {:text => 'satirical', :meaning => 'exposing human folly to ridicule'},
          {:text => 'saturnine', :meaning => 'bitter or scornful'},
          {:text => 'saurian', :meaning => 'of or relating to lizards'},
          {:text => 'scabrous', :meaning => 'rough to the touch'},
          {:text => 'scaffolding', :meaning => 'a system of scaffolds'},
          {:text => 'scalpel', :meaning => 'a thin straight surgical knife used in dissection and surgery'},
          {:text => 'scenarist', :meaning => 'a writer of screenplays'},
          {:text => 'scheduling', :meaning => 'setting an order and time for planned events'},
          {:text => 'schismatic', :meaning => 'of or relating to or involved in or characteristic of schism'},
          {:text => 'schizophrenia', :meaning => 'any of several psychotic disorders characterized by distortions of reality and disturbances of thought and language and withdrawal from social contact'},
          {:text => 'scintilla', :meaning => 'a tiny or scarcely detectable amount'},
          {:text => 'scofflaw', :meaning => 'one who habitually ignores the law and does not answer court summonses'},
          {:text => 'scrivener', :meaning => 'someone employed to make written copies of documents and manuscripts'},
          {:text => 'scurrilous', :meaning => 'expressing offensive reproach'},
          {:text => 'secretion', :meaning => 'the organic process of synthesizing and releasing some substance'},
          {:text => 'sediment', :meaning => 'matter that has been deposited by some natural process'},
          {:text => 'seditious', :meaning => 'arousing to action or rebellion'},
          {:text => 'seepage', :meaning => 'the process of seeping'},
          {:text => 'seismography', :meaning => 'the measurement of tremors and shocks and undulatory movements of earthquakes'},
          {:text => 'semaphore', :meaning => 'an apparatus for visual signaling with lights or mechanically moving arms v 1: send signals by or as if by semaphore'},
          {:text => 'sequester', :meaning => 'requisition forcibly, as of enemy property'},
          {:text => 'serendipity', :meaning => 'good luck in making unexpected and fortunate discoveries'},
          {:text => 'sextuplet', :meaning => 'the cardinal number that is the sum of five and one'},
          {:text => 'skedaddle', :meaning => 'a hasty flight v 1: run away, as if in a panic'},
          {:text => 'sonorous', :meaning => 'full and loud and deep'},
          {:text => 'sophistry', :meaning => 'a deliberately invalid argument displaying ingenuity in reasoning in the hope of deceiving someone'},
          {:text => 'soporific', :meaning => 'sleep inducing'},
          {:text => 'soubrette', :meaning => 'a pert or flirtatious young girl'},
          {:text => 'soupcon', :meaning => 'a slight but appreciable amount'},
          {:text => 'splenetic', :meaning => 'of or relating to the spleen'},
          {:text => 'spurious', :meaning => 'plausible but false'},
          {:text => 'staccato', :meaning => 'separating the notes'},
          {:text => 'stalagmite', :meaning => 'a cylinder of calcium carbonate projecting upward from the floor of a limestone cave'},
          {:text => 'statuesque', :meaning => 'of size and dignity suggestive of a statue'},
          {:text => 'stealthily', :meaning => 'in a stealthy manner'},
          {:text => 'stenosis', :meaning => 'abnormal narrowing of a bodily canal or passageway'},
          {:text => 'sternum', :meaning => 'the flat bone that articulates with the clavicles and the first seven pairs of ribs'},
          {:text => 'stethoscope', :meaning => 'a medical instrument for listening to the sounds generated inside the body'},
          {:text => 'stigmatism', :meaning => 'the condition of having or being marked by stigmata'},
          {:text => 'stipple', :meaning => 'engrave by means of dots and flicks'},
          {:text => 'stoolie', :meaning => 'someone acting as an informer or decoy for the police'},
          {:text => 'stricture', :meaning => 'abnormal narrowing of a bodily canal or passageway'},
          {:text => 'strychnine', :meaning => 'an alkaloid plant toxin extracted chiefly from nux vomica'},
          {:text => 'stultify', :meaning => "prove to be of unsound mind or demonstrate someone's incompetence"},
          {:text => 'stupefy', :meaning => 'make dull or stupid or muddle with drunkenness or infatuation'},
          {:text => 'stygian', :meaning => 'hellish'},
          {:text => 'subaltern', :meaning => 'inferior in rank or status'},
          {:text => 'subliminal', :meaning => 'below the threshold of conscious perception'},
          {:text => 'subsistence', :meaning => 'minimal (or marginal) resources for subsisting'},
          {:text => 'subterfuge', :meaning => 'something intended to misrepresent the true nature of an activity'},
          {:text => 'succotash', :meaning => 'fresh corn and lima beans with butter or cream'},
          {:text => 'suffragan', :meaning => 'an assistant or subordinate bishop of a diocese'},
          {:text => 'superficies', :meaning => 'the purely external aspect of a thing'},
          {:text => 'surname', :meaning => "the name used to identify the members of a family (as distinguished from each member's given name) "},
          {:text => 'surveillance', :meaning => 'close observation of a person or group (usually by the police)'},
          {:text => 'swizzle', :meaning => 'any of various tall frothy mixed drinks made usually of rum and lime juice and sugar shaken with ice'},
          {:text => 'sycophant', :meaning => 'a person who tries to please someone in order to gain a personal advantage'},
          {:text => 'syllepsis', :meaning => 'use of a word to govern two or more words though agreeing in number or case etc. with only one'},
          {:text => 'syncopation', :meaning => "(phonology) the loss of sounds from within a word (as in `fo'c'sle' for `forecastle')"},
          {:text => 'tertian', :meaning => 'relating to symptoms (especially malarial fever) that appear every other day'},
          {:text => 'testaceous', :meaning => 'relating to or possessing a testa or hard shell'},
          {:text => 'thaumaturgy', :meaning => 'any art that invokes supernatural powers'},
          {:text => 'theocracy', :meaning => 'a political unit governed by a deity (or by officials thought to be divinely guided)'},
          {:text => 'theosophy', :meaning => 'a system of belief based on mystical insight into the nature of God and the soul'},
          {:text => 'therapeutic', :meaning => 'tending to cure or restore to health'},
          {:text => 'thesaurus', :meaning => 'a book containing a classified list of synonyms'},
          {:text => 'thrombosis', :meaning => 'the formation or presence of a thrombus (a clot of coagulated blood attached at the site of its formation) in a blood vessel'},
          {:text => 'tintinnabulation', :meaning => 'the sound of a bell ringing'},
          {:text => 'titillate', :meaning => 'touch (a body part) lightly so as to excite the surface nerves and cause uneasiness, laughter, or spasmodic movements'},
          {:text => 'tonsillitis', :meaning => 'inflammation of the tonsils (especially the palatine tonsils)'},
          {:text => 'torrential', :meaning => 'relating to or resulting from the action of a torrent'},
          {:text => 'torsion', :meaning => 'a tortuous and twisted shape or position'},
          {:text => 'triceps', :meaning => 'any skeletal muscle having three origins (but especially the triceps brachii)'},
          {:text => 'trichinosis', :meaning => 'infestation by trichina larvae that are transmitted by eating inadequately cooked meat (especially pork)'},
          {:text => 'tricuspid', :meaning => 'having three cusps or points (especially a molar tooth)'},
          {:text => 'tripartite', :meaning => 'involving three parties or elements'},
          {:text => 'tumefaction', :meaning => 'the process of tumefying'},
          {:text => 'tumultuous', :meaning => 'characterized by unrest or disorder or insubordination'},
          {:text => 'turpitude', :meaning => 'a corrupt or depraved or degenerate act or practice'},
          {:text => 'ubiquitous', :meaning => 'being present everywhere at once'},
          {:text => 'umbrage', :meaning => 'a feeling of anger caused by being offended'},
          {:text => 'unctuous', :meaning => 'unpleasantly and excessively suave or ingratiating in manner or speech'},
          {:text => 'underrate', :meaning => 'make too low an estimate of'},
          {:text => 'undulation', :meaning => 'an undulating curve'},
          {:text => 'unguent', :meaning => 'semisolid preparation (usually containing a medicine) applied externally as a remedy or for soothing an irritation'},
          {:text => 'unintelligible', :meaning => 'poorly articulated or enunciated, or drowned by noise'},
          {:text => 'unparalleled', :meaning => 'radically distinctive and without equal'},
          {:text => 'usurper', :meaning => 'one who wrongfully or illegally seizes and holds the place of another'},
          {:text => 'uxorious', :meaning => 'foolishly fond of or submissive to your wife'},
          {:text => 'vacillate', :meaning => 'be undecided about something'},
          {:text => 'valetudinarian', :meaning => 'of or relating to or characteristic of a person who is a valetudinarian'},
          {:text => 'vapidity', :meaning => 'the quality of being vapid and unsophisticated'},
          {:text => 'variegated', :meaning => 'having a variety of colors'},
          {:text => 'venality', :meaning => 'prostitution of talents or offices or services for reward'},
          {:text => 'verdigris', :meaning => 'a blue or green powder used as a paint pigment'},
          {:text => 'verisimilitude', :meaning => 'the appearance of truth'},
          {:text => 'vermicular', :meaning => 'decorated with wormlike tracery or markings'},
          {:text => 'versatile', :meaning => 'having great diversity or variety'},
          {:text => 'vertebrate', :meaning => 'having a backbone or spinal column'},
          {:text => 'vichyssoise', :meaning => 'a creamy potato soup flavored with leeks and onions'},
          {:text => 'vicissitude', :meaning => 'a variation in circumstances or fortune at different times in your life or in the development of something'},
          {:text => 'vignette', :meaning => 'a brief literary description'},
          {:text => 'virility', :meaning => 'the masculine property of being capable of copulation and procreation'},
          {:text => 'virulent', :meaning => 'extremely poisonous or injurious'},
          {:text => 'viscous', :meaning => 'having a relatively high resistance to flow'},
          {:text => 'vitiate', :meaning => 'corrupt morally or by intemperance or sensuality'},
          {:text => 'vitreous', :meaning => 'of or relating to or constituting the vitreous humor of the eye'},
          {:text => 'vituperative', :meaning => 'marked by harshly abusive criticism'},
          {:text => 'vociferous', :meaning => 'conspicuously and offensively loud'},
          {:text => 'volatile', :meaning => 'evaporating readily at normal temperatures and pressures'},
          {:text => 'voracious', :meaning => 'excessively greedy and grasping'},
          {:text => 'vulpine', :meaning => 'resembling or characteristic of a fox'},
          {:text => 'warmonger', :meaning => 'a person who advocates war or warlike policies'},
          {:text => 'watercress', :meaning => 'of a moderate yellow-green color that is greener and deeper than moss green and yellower and darker than pea green'},
          {:text => 'whimsicality', :meaning => 'the trait of acting unpredictably and more from whim or caprice than from reason or judgment'},
          {:text => 'whippoorwill', :meaning => 'American nocturnal goatsucker with grey-and-white plumage'},
          {:text => 'whirligig', :meaning => "a conical child's plaything tapering to a steel point on which it can be made to spin"},
          {:text => 'witticism', :meaning => 'a message whose ingenuity or verbal skill or incongruity has the power to evoke laughter'},
          {:text => 'xylophone', :meaning => 'a percussion instrument with wooden bars tuned to produce a chromatic scale and with resonators'},
          {:text => 'zodiacal', :meaning => 'relating to or included in the zodiac'},
          {:text => 'zoological', :meaning => 'concerning the study of animals and their classification and properties'}
)

